services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    ####################################################################################################
    # Mailpit
    ####################################################################################################
    mail:
        image: axllent/mailpit:latest
        ports:
        - 8025:8025
        - 1025:1025

    ####################################################################################################
    # Redis
    ####################################################################################################
    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
        - .docker/redis/data:/data
        ports:
        - 6379:6379

    ####################################################################################################
    # PostgreSQL
    ####################################################################################################
    db:
         image: postgres:16
         ports:
             - 5432:5432
         volumes:
             - .docker/db/data:/var/lib/postgresql/data
             - .docker/db/sql:/docker-entrypoint-initdb.d
         environment:
             - POSTGRES_USER=${DB_USERNAME}
             - POSTGRES_PASSWORD=${DB_PASSWORD}
             - POSTGRES_DB=${DB_DATABASE}

    ####################################################################################################
    # pgAdmin
    ####################################################################################################
    pgadmin:
         image: dpage/pgadmin4
         ports:
             - 5050:80
         environment:
             - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
             - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
         depends_on:
             - db
